---
title: Demo Grading Contract
output: github_document
params:
  weekonemonday: "2022-01-10"
  name: John Bennett
---

```{r setup, include=FALSE}

# R Syllabus Scheduler

advdate <- function(obj,
                    adv,
                    topic =  NULL,
                    assignment=NULL,
                    unit="Module ") {
  tmon <- obj + 7*(adv-1)
  ttue <- obj + 1 + 7*(adv-1)
  twed <- obj + 2 + 7*(adv-1)
  tthu <- obj + 3 + 7*(adv-1)
  tfri <- obj + 4 + 7*(adv-1)
  tmon <- format(tmon, format="%m/%d")
  ttue <- format(ttue, format="%m/%d")
  twed <- format(twed, format="%m/%d")
  tthu <- format(tthu, format="%m/%d")
  tfri <- format(tfri, format="%m/%d")
  zadv <- sprintf("%02d", adv)

  if (is.null(topic)&is.null(assignment)){
    tmp <- paste(unit,zadv,sep='',", ", tmon," - ",tfri)
  } else if(!is.null(assignment)){
    if(assignment %in%
       c("Friday",
         "friday",
         "f",
         "fri",
         "FRI")
       ){
    tmp <- paste0(tfri)
  } else if(assignment %in%
            c("thursday",
              "Thursday",
              "thurs",
              "r",
              "R")){
    tmp <- paste0(tthu)
  }else if(assignment %in%
           c("wednesday",
             "Wednesday",
             "w",
             "wed",
             "W")
           ){
    tmp <- paste0(twed)
  } else if(assignment %in%
            c("Tuesday",
              "tues",
              "t",
              "Tue")){
    tmp <- paste0(ttue)
  }else if(assignment %in%
            c("monday",
              "Monday",
              "m")
            ){
    tmp <- paste0(tmon)
  }
  }else{
    tmp <- paste(unit,zadv,sep='',", ", tmon," - ",tfri, " : ", topic[adv])
    }
  return(tmp)
}


dayone <- as.Date(params$weekonemonday)

topic=c(
  "What is Data Science and Meet the Toolkit", 
  "Data and Visualization",
  "Grammar of data wrangling",
  "Data types and Data Transformations",
  "Tips for effective data visualization",
  "Scientific studies and confounding",#  "Spring Break",#  "",
  "Web scraping", 
  "Functions", 
  "Data and Ethics",
  "Fitting and interpreting models",
  "Prediction and overfitting", 
  "Cross validation", 
  "Quantifying uncertainty",
  "Interactive web apps",
  "Special Topics" 
  )

```

<!-- This contract is adapted from Annie Somerville's contract https://github.com/anniehsom -->



# Contract Grades – “A” Contract

I, John T. Bennett, agree to :

1) Earn “Satisfactory” on 11 self-paced lab assignments on the schedule specified below.
	-  Satisfactory defined:
  	-  I have attempted all steps of the assignment. If unable to complete steps due to unresolved questions, I have asked questions in Github FAQs or zoom help session, or I have Googled the issue and shown effort to resolve questions;
  	-  I have checked that forked files, repos, or projects appear on my Github account and are accessible;
  	-  I feel like I have spent an adequate amount of time and energy on assignments; 
<!-- (tentatively defining “adequate” based on Lab 1 and previous experience with R: I will spend at least 30 minutes on labs and at least 1 hour on portfolio pieces); -->
  	-  My unessays are organized, thoughtful, and free of grammar mistakes or typos;
  	-  My presentation is professional and engaging.
2) Produce at least 10 “Satisfactory” portfolio pieces on the schedule specified below.
3) Complete two “Satisfactory” Unessays on the schedule specified below.
4) Complete a “Satisfactory” presentation based on the strongest of the two unessays. 10 minutes total in length.



## SCHEDULE

-   [ ] Module 01, 01/10 - 02/02 : What is Data Science and Meet the
    Toolkit
    -   Finish Lab 1 by 02/08

-   [ ] Module 02, 02/07 - 02/11 : Data and Visualization
    -   Finish Lab 2 by 02/11

-   [ ] Module 03, 02/07 - 02/11 : Grammar of data wrangling

-   [ ] Module 04, 02/14 - 02/18 : Data types and Data Transformations
    -   Finish Lab 3 by 02/18
    -   Finish Lab 4 by 02/18
    
-   [ ] Module 05, 02/14 - 02/18 : Tips for effective data visualization
    -   Finish Lab 5 by 02/25

-   [ ] Module 06, 02/21 - 02/25 : Scientific studies and confounding
    -   Finish Lab 6 by 02/25
    -   Finish portfolio piece 1 by 02/25
    
-   [ ] Module 07, 02/21 - 02/25 : Web scraping
    -   Finish Lab 7 by 02/25
    -   Finish portfolio piece 2 by 02/25
    
-   [ ] Module 08, 02/28 - 03/04 : Functions
    -   Finish Lab 8 by 03/04
    -   Finish portfolio piece 3 by 03/04
    -   Finish Unessay 1 due on 03/04
    
-   [ ] Module 09, 03/07 - 03/11 : Data and Ethics
    -   Finish Lab 9 by 03/11
    -   Finish portfolio piece 4 by 03/11
    
-   [ ] Module 10, 03/14 - 03/18 : Fitting and interpreting models
    -   Finish Lab 10 by 03/18
    
-   [ ] Module 11, 03/21 - 03/25 : Prediction and overfitting
    -   Finish Lab 11 by 03/25
    -   Finish portfolio piece 5 by 03/25
    
-   [ ] Module 12, 03/28 - 04/01 : Cross validation
    -   Finish Lab 12 by 04/01
    -   Finish portfolio piece 6 by 04/01
    
-   [ ] Module 13, 04/04 - 04/08 : Quantifying uncertainty
    -   Finish portfolio pieces 7 and 8 by 04/08
    
-   [ ] Module 14, 04/11 - 04/15 : Interactive web apps
    -   Finish portfolio piece 9 by 04/15
    
-   [ ] Module 15, 04/18 - 04/22 : Special Topics
    -   Finish portfolio piece 10 by 04/22
    -   Finish Unessay 2 due on 04/22
    
-   [ ] Portfolio completion and end-of-semester presentation
    -   Due on 04/22


